spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testDB
    username : sa
    password :
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #      table을 자동으로 만들어는 모드
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
#server:
#  port: 8083